### PR TITLE
Document styles, plugins

### PR DESCRIPTION
**Pull request by machikoyasuda**
Add `styles`, `plugins` to readme.

### CODE REVIEW

**Comment by jshimko** [comment]
These are all internal functionality that I'm not sure we want people to be using (which is why they're not in the readme).  For example, the config command would allow you to overwrite configs that Launchdock currently depends on.  I originally only exposed these so they could be used in automation setups and I can see plenty of scenarios where people may want to use these for their own automation, but I don't think these API's are ready/stable enough to start recommending yet.  The only reason you see them when you run `reaction --help` is because the [arg parser library I used](https://github.com/yargs/yargs) automatically assembles the help output and you can't customize it.

**Comment by machikoyasuda** [comment]
What about `styles` and `plugins`? I can take out `config`.

**Comment by jshimko** [comment]
They both automatically run [every time you run](https://github.com/reactioncommerce/reaction-cli/blob/master/src/commands/run.js#L61-L65) `reaction` or `reaction run`.  I guess we can add them, but I suspect it'll raise more questions than anything else.  Nobody ever needs to manually run those commands unless they're doing something fairly advanced.  I guess it doesn't hurt though.  You certainly can't break anything with those commands.

**Comment by machikoyasuda** [comment]
I'm going to be documenting `reaction plugin` commands in the updated plugin tutorial, example: https://github.com/machikoyasuda/reaction-sticky-footer-plugin#make-this-plugin-yourself

**Comment by aaronjudd** [comment]
I'm with @jshimko those are private internal methods and should probably not be published/documented right now as they are likely to deprecate or change.  I'd be careful with the specifics of plugin loading process,  as we're going to be greatly overhauling those very soon, in a way that should be transparent (but not if we expose too much ;-) ).

**Pull request closed without merging**
