### PR TITLE
0.30.1

### PR DESCRIPTION
**Pull request by focusaurus**
Bumping for circleci/npm fixes

### CODE REVIEW

**Comment by focusaurus** [comment]
I'm going to close this and start over. The yeoman stuff we have is more cost than benefit for this project and I have to grok every line anyway to get it to work.

**Comment by loan-laux** [comment]
@focusaurus Any ETA on this? Having the custom debugger port flags available on the NPM version would be very helpful for debugging in Docker. Let me know if I can help in any way as I understand that this isn't a priority.

**Comment by focusaurus** [comment]
Sorry for the delay @loan-laux . It's not code issues causing delay, it's our CI/npm tooling has gotten out of date for this and I need to fix that up. Still on my radar to try to get this released though. Hang in there!

**Comment by loan-laux** [comment]
@focusaurus Understood, thanks for the status!

**Pull request closed without merging**
